// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

#include "stdafx.h"


BOOL APIENTRY DllMain(
    HMODULE module,
    DWORD reason,
    LPVOID reserved)
{
    UNREFERENCED_PARAMETER(module);
    UNREFERENCED_PARAMETER(reserved);

    switch (reason)
    {
        case DLL_PROCESS_ATTACH:
        case DLL_THREAD_ATTACH:
        case DLL_THREAD_DETACH:
        case DLL_PROCESS_DETACH:
            break;
    }
    return TRUE;
}


//
// WARNING: 
//
// The signature below MUST exactly match (including the parameter names)
// with the signature generated by MIDL in the FabricServiceCommunication.h file. 
// Otherwise the linker does not apply the extern "C" specifier and exports 
// this function as C++ name mangled function instead of C style function.
// 
/* [entry] */ HRESULT CreateServiceCommunicationListener(
    /* [in] */ __RPC__in REFIID interfaceId,
    /* [in] */ __RPC__in  FABRIC_SERVICE_TRANSPORT_SETTINGS *settings,
    /* [in] */ __RPC__in FABRIC_SERVICE_LISTENER_ADDRESS *address,
    /* [in] */ __RPC__in  IFabricCommunicationMessageHandler *clientRequestHandler,
    /* [in] */ __RPC__in IFabricServiceConnectionHandler *clientConnectionHandler,
    /* [out, retval] */ __RPC__deref_out_opt IFabricServiceCommunicationListener ** listener)
{
    auto &providerFactory = Communication::TcpServiceCommunication::ServiceCommunicationListenerFactory::GetServiceCommunicationListenerFactory();

    Api::ComFabricServiceCommunicationListenerFactory comFactory(providerFactory);

    return comFactory.CreateFabricServiceCommunicationListener(interfaceId, settings, address,clientRequestHandler, clientConnectionHandler, listener);
}


HRESULT CreateServiceCommunicationClient(
    /* [in] */ __RPC__in REFIID interfaceId,
    /* [in] */ __RPC__in FABRIC_SERVICE_TRANSPORT_SETTINGS *settings,
    /* [in] */ __RPC__in LPCWSTR connectionAddress,
    /* [in] */ __RPC__in IFabricCommunicationMessageHandler *notificationHandler,
    /* [in] */ __RPC__in IFabricServiceConnectionEventHandler *connectionEventHandler,
    /* [out, retval] */ __RPC__deref_out_opt IFabricServiceCommunicationClient **client)
{
    auto clientFactoryPtr = Communication::TcpServiceCommunication::ServiceCommunicationClientFactory::Create();

    Api::ComFabricServiceCommunicationClientFactory comFactory(clientFactoryPtr);

    return  comFactory.CreateFabricServiceCommunicationClient(interfaceId, connectionAddress, settings, notificationHandler, connectionEventHandler,client);

}
