#undef utf8to16
#undef utf8to16
#undef utf16to8
#undef CreateEventW
#undef EventRegister
#undef EventDataDescCreate
#undef EventWrite
#undef ResetEvent
#undef WaitForSingleObject
#undef NtQuerySystemInformation
#undef CloseHandle
#undef HeapDestroy
#undef VirtualAlloc
#undef VirtualFree
#undef RtlCompareMemory
#undef RtlMoveMemory
#undef RtlZeroMemory
#undef InitializeSRWLock
#undef AcquireSRWLockExclusive
#undef TryAcquireSRWLockExclusive
#undef AcquireSRWLockShared
#undef TryAcquireSRWLockShared
#undef ReleaseSRWLockExclusive
#undef ReleaseSRWLockShared
#undef GetProcessHeap
#undef SetLastError
#undef GetCurrentThreadId
#undef HeapCreate
#undef DbgPrintEx
#undef HeapAlloc
#undef HeapFree
#undef EventEnabled
#undef memcpy_s
#undef GetModuleFileNameW
#undef CreateThread
#undef InitializeThreadpoolEnvironment
#undef DestroyThreadpoolEnvironment
#undef SetThreadpoolCallbackPool
#undef CreateThreadpool
#undef CloseThreadpool
#undef SetThreadpoolThreadMinimum
#undef SetThreadpoolThreadMaximum
#undef CreateThreadpoolWork
#undef CloseThreadpoolWork
#undef SubmitThreadpoolWork
#undef WaitForThreadpoolWorkCallbacks
#undef GetLastError
#undef DebugBreak
#undef GetCurrentProcess
#undef GetCurrentProcessorNumber
#undef GetProcessAffinityMask
#undef OpenThread
#undef SetThreadAffinityMask
#undef SetThreadPriority
#undef SleepEx
#undef RtlMultiByteToUnicodeSize
#undef RtlMultiByteToUnicodeN
#undef UuidCreate
#undef RtlExtendedMagicDivide
#undef RtlExtendedIntegerMultiply
#undef ElapsedDaysToYears
#undef TimeToDaysAndFraction
#undef RtlTimeToTimeFields
#undef DaysAndFractionToTime
#undef RtlTimeFieldsToTime
#undef FileTimeToSystemTime
#undef FILEUnixTimeToFileTime
#undef GetSystemTimeAsFileTime
#undef RtlMultiByteToUnicodeSize
#undef RtlMultiByteToUnicodeN
#undef NtQueryVolumeInformationFile
#undef NtOpenDirectoryObject
#undef NtOpenSymbolicLinkObject
#undef NtQuerySymbolicLinkObject
#undef NtQueryDirectoryObject
#undef QueryPerformanceFrequency
#undef QueryPerformanceCounter
#undef PerfCreateInstance
#undef PerfSetCounterRefValue
#undef PerfDeleteInstance
#undef PerfSetCounterSetInfo
#undef PerfStartProviderEx
#undef PerfStopProvider
#undef GetSystemInfo
#undef RtlCreateSecurityDescriptor
#undef RtlLengthSid
#undef RtlCreateAcl
#undef RtlAddAccessAllowedAce
#undef RtlSetDaclSecurityDescriptor
#undef GetCurrentThread
#undef OpenThreadToken
#undef OpenProcessToken
#undef DuplicateTokenEx
#undef SetThreadToken
#undef AdjustTokenPrivileges
#undef WriteFile
#undef ReadFile
#undef RegOpenKeyExW
#undef RegCloseKey
#undef RegQueryValueExW
#undef RegSetValueExW
#undef RegDeleteValueW
#undef SetThreadpoolTimer
#undef CloseThreadpoolTimer
#undef CreateThreadpoolTimer
#undef WaitForThreadpoolTimerCallbacks
#undef RtlStringCchCatW
#undef RtlStringCchLengthW
#undef RtlStringCchCopyW
#undef GetEnvironmentVariableA
#undef GetEnvironmentVariableW
#undef ExpandEnvironmentStringsA
#undef ExpandEnvironmentStringsW
#undef RtlRandomEx
#undef VirtualProtect
#undef WaitForMultipleObjects
#undef SymInitialize
#undef CaptureStackBackTrace
#undef SymFromAddr
#undef SymGetLineFromAddr64
#undef NtCreateFile
#undef NtDeleteFile
#undef NtClose
#undef NtOpenFile
#undef NtQueryInformationFile
#undef NtQueryFullAttributesFile
#undef NtSetInformationFile
#undef NtFsControlFile
#undef NtDeviceIoControlFile
#undef NtWriteFile
#undef NtReadFile
#undef NtFlushBuffersFile
#undef NtWaitForSingleObject
#undef NtQueryDirectoryFile
#undef NtCreateEvent
#undef WriteFileGather
#undef ReadFileScatter

