// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------

#include "Common/Common.h"
#include "Transport/Transport.h"
#include "Federation/Federation.h"
#include "query/Query.h"
#include "Hosting2/Hosting.h"
#include "systemservices/SystemServices.Messages.h"
#include "ServiceModel/ServiceModel.h"
#include "Store/store.h"

#include "Management/Common/ManagementCommon.h"
#include "Management/ImageModel/ImageModel.h"

#include "Management/healthmanager/Constants.h"
#include "Management/healthmanager/HealthEntityKind.h"
#include "Management/healthmanager/HealthManagerPointers.h"
#include "Management/healthmanager/HealthManagerPointers.Internal.h"
#include "Management/healthmanager/IRequestContextProcessor.h"
#include "Management/healthmanager/RequestContextKind.h"
#include "Management/healthmanager/RequestContext.h"
#include "Management/healthmanager/ReportRequestContext.h"
#include "Management/healthmanager/EntityStateFlags.h"
#include "Management/healthmanager/EntityJobItemState.h"
#include "Management/healthmanager/HealthJobItemKind.h"
#include "Management/healthmanager/IHealthJobItem.h"
#include "Management/healthmanager/AttributesStoreData.h"
#include "Management/healthmanager/ClusterAttributesStoreData.h"
#include "Management/healthmanager/ReplicatedStoreWrapper.h"
#include "Management/healthmanager/HealthCount.h"
#include "Management/healthmanager/GroupHealthStateCount.h"

#include "Management/healthmanager/ReplicaHealthId.h"
#include "Management/healthmanager/ServiceHealthId.h"
#include "Management/healthmanager/ApplicationHealthId.h"
#include "Management/healthmanager/DeployedApplicationHealthId.h"
#include "Management/healthmanager/DeployedServicePackageHealthId.h"
#include "Management/healthmanager/HealthEventStoreData.h"
#include "Management/healthmanager/EntityHealthEventStoreData.h"
#include "Management/healthmanager/NodeAttributesStoreData.h"
#include "Management/healthmanager/PartitionAttributesStoreData.h"
#include "Management/healthmanager/ReplicaAttributesStoreData.h"
#include "Management/healthmanager/ServiceAttributesStoreData.h"
#include "Management/healthmanager/ApplicationAttributesStoreData.h"
#include "Management/healthmanager/DeployedServicePackageAttributesStoreData.h"
#include "Management/healthmanager/DeployedApplicationAttributesStoreData.h"
#include "Management/healthmanager/SequenceStreamStoreData.h"
#include "Management/healthmanager/QueryRequestContext.h"
#include "Management/healthmanager/SequenceStreamRequestContext.h"

#include "Management/healthmanager/healthmanager.h"
#include "Management/healthmanager/HealthManagerReplica.h"

#include "Management/healthmanager/HealthEntityChildren.h"
#include "Management/healthmanager/HealthEntityParent.h"
#include "Management/healthmanager/HealthEntityState.h"
#include "Management/healthmanager/HealthEntity.h"
#include "Management/healthmanager/ClusterEntity.h"
#include "Management/healthmanager/NodeEntity.h"
#include "Management/healthmanager/PartitionEntity.h"
#include "Management/healthmanager/ReplicaEntity.h"
#include "Management/healthmanager/ServiceEntity.h"
#include "Management/healthmanager/DeployedServicePackageEntity.h"
#include "Management/healthmanager/DeployedApplicationEntity.h"
#include "Management/healthmanager/ApplicationEntity.h"

#include "Management/healthmanager/HealthManagerCommonEventSource.h"

#include "Management/healthmanager/EntityJobQueueManager.h"

#include "Management/healthmanager/HealthEntityCache.h"
#include "Management/healthmanager/NodesCache.h"
#include "Management/healthmanager/PartitionsCache.h"
#include "Management/healthmanager/ReplicasCache.h"
#include "Management/healthmanager/ServicesCache.h"
#include "Management/healthmanager/DeployedServicePackagesCache.h"
#include "Management/healthmanager/DeployedApplicationsCache.h"
#include "Management/healthmanager/ApplicationsCache.h"
#include "Management/healthmanager/ClusterCache.h"
#include "Management/healthmanager/EntityCacheManager.h"

#include "Management/healthmanager/ProcessRequestAsyncOperation.h"

#include "Management/healthmanager/HealthManagerEventSource.h"
