
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a dotnet run from src\ResGen folder.
//     To add or remove a member, edit your .resx file then rerun src\ResGen.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace System.Fabric.BackupRestore {

using System;
using System.Reflection;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]

internal class SR {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal SR() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Fabric.BackupRestore.SR", typeof(SR).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current threads CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    

    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Periodic backup successfully disabled
    ///  
    /// </summary>
    internal static string Clear_Backup_Health {
        get {
            return ResourceManager.GetString("Clear_Backup_Health", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Failed to take periodic backup for this partition with error:\n{0}
    ///  
    /// </summary>
    internal static string Error_BackupFailure_HealthMsg {
        get {
            return ResourceManager.GetString("Error_BackupFailure_HealthMsg", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Recovery point metadata file cannot be deserialized (unknown version number: {0}, expected version number: {1}).
    ///  
    /// </summary>
    internal static string Error_BackupMetadata_Deserialized {
        get {
            return ResourceManager.GetString("Error_BackupMetadata_Deserialized", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Block extends beyond end of the stream.
    ///  
    /// </summary>
    internal static string Error_Block_Beyond_Stream {
        get {
            return ResourceManager.GetString("Error_Block_Beyond_Stream", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Checksum Mismatch.
    ///  
    /// </summary>
    internal static string Error_Checksum_Mismatch {
        get {
            return ResourceManager.GetString("Error_Checksum_Mismatch", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    A block of the file is corrupt ({0}).
    ///  
    /// </summary>
    internal static string Error_FileBlock_Corrupt {
        get {
            return ResourceManager.GetString("Error_FileBlock_Corrupt", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    File path does not exist: {0}.
    ///  
    /// </summary>
    internal static string Error_FilePath_Null {
        get {
            return ResourceManager.GetString("Error_FilePath_Null", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    File properties section is corrupt ({0}).
    ///  
    /// </summary>
    internal static string Error_FileProperties_Corrupt {
        get {
            return ResourceManager.GetString("Error_FileProperties_Corrupt", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Property size extends beyond the section.
    ///  
    /// </summary>
    internal static string Error_FileProperties_LargeSize {
        get {
            return ResourceManager.GetString("Error_FileProperties_LargeSize", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Property size is negative.
    ///  
    /// </summary>
    internal static string Error_FileProperties_NegativeSize {
        get {
            return ResourceManager.GetString("Error_FileProperties_NegativeSize", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Incorrect section size.
    ///  
    /// </summary>
    internal static string Error_FileProperties_SectionSize {
        get {
            return ResourceManager.GetString("Error_FileProperties_SectionSize", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Negative block size.
    ///  
    /// </summary>
    internal static string Error_Negative_BlockSize {
        get {
            return ResourceManager.GetString("Error_Negative_BlockSize", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Negative stream offset
    ///  
    /// </summary>
    internal static string Error_Negative_StreamOffset {
        get {
            return ResourceManager.GetString("Error_Negative_StreamOffset", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Argument {0} must not be null.
    ///  
    /// </summary>
    internal static string Error_NullArgument_Formatted {
        get {
            return ResourceManager.GetString("Error_NullArgument_Formatted", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Failed to restore partition automatically after encountering data loss with error:\n{0}
    ///  
    /// </summary>
    internal static string Error_RestoreFailure_HealthMsg {
        get {
            return ResourceManager.GetString("Error_RestoreFailure_HealthMsg", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Partition successfully backed up at {0} GMT
    ///  
    /// </summary>
    internal static string Success_Backup_HealthMsg {
        get {
            return ResourceManager.GetString("Success_Backup_HealthMsg", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Partition was successfully restored at {0} GMT after encountering a data loss event.
    ///  
    /// </summary>
    internal static string Success_Restore_DataLoss_HealthMsg {
        get {
            return ResourceManager.GetString("Success_Restore_DataLoss_HealthMsg", resourceCulture);
        }
    }


    /// <summary>
    ///   Looks up a localized string similar to 
    ///    Partition was successfully restored at {0} GMT.
    ///  
    /// </summary>
    internal static string Success_Restore_UserInitiated_HealthMsg {
        get {
            return ResourceManager.GetString("Success_Restore_UserInitiated_HealthMsg", resourceCulture);
        }
    }

}

}

